### ISSUE TITLE
failed: IntegrationTest - Address already in use

### ISSUE THREAD

**Issue by patriknw** [akka/akka-platform-guide#352]
03 Shopping cart service (Java)

```
Running shopping.cart.IntegrationTest
290[2020-10-22 09:43:44,243] [INFO] [akka.event.slf4j.Slf4jLogger] [] [] [IntegrationTest-akka.actor.default-dispatcher-3] - Slf4jLogger started
291[2020-10-22 09:43:45,673] [INFO] [akka.remote.artery.tcp.ArteryTcpTransport] [akka://IntegrationTest] [] [IntegrationTest-akka.actor.default-dispatcher-3] - Remoting started with transport [Artery tcp]; listening on address [akka://IntegrationTest@127.0.0.1:44325] with UID [-6022436335997463111]
292[2020-10-22 09:43:45,756] [INFO] [akka.cluster.Cluster] [akka://IntegrationTest@127.0.0.1:44325] [] [IntegrationTest-akka.actor.default-dispatcher-3] - Cluster Node [akka://IntegrationTest@127.0.0.1:44325] - Starting up, Akka version [2.6.10] ...
293[2020-10-22 09:43:46,131] [INFO] [akka.cluster.Cluster] [akka://IntegrationTest@127.0.0.1:44325] [] [IntegrationTest-akka.actor.default-dispatcher-3] - Cluster Node [akka://IntegrationTest@127.0.0.1:44325] - Registered cluster JMX MBean [akka:type=Cluster,port=44325]
294[2020-10-22 09:43:46,131] [INFO] [akka.cluster.Cluster] [akka://IntegrationTest@127.0.0.1:44325] [] [IntegrationTest-akka.actor.default-dispatcher-3] - Cluster Node [akka://IntegrationTest@127.0.0.1:44325] - Started up successfully
295[2020-10-22 09:43:46,398] [INFO] [akka.cluster.Cluster] [akka://IntegrationTest@127.0.0.1:44325] [] [IntegrationTest-akka.actor.default-dispatcher-5] - Cluster Node [akka://IntegrationTest@127.0.0.1:44325] - No seed-nodes configured, manual cluster join required, see https://doc.akka.io/docs/akka/current/typed/cluster.html#joining
296[2020-10-22 09:43:46,421] [INFO] [akka.cluster.sbr.SplitBrainResolver] [akka://IntegrationTest@127.0.0.1:44325] [] [IntegrationTest-akka.actor.default-dispatcher-3] - SBR started. Config: strategy [KeepMajority], stable-after [20 seconds], down-all-when-unstable [15 seconds], selfUniqueAddress [akka://IntegrationTest@127.0.0.1:44325#-6022436335997463111], selfDc [default].
297[2020-10-22 09:43:47,359] [INFO] [akka.event.slf4j.Slf4jLogger] [] [] [IntegrationTest-akka.actor.default-dispatcher-3] - Slf4jLogger started
298[2020-10-22 09:43:47,405] [INFO] [akka.remote.artery.tcp.ArteryTcpTransport] [akka://IntegrationTest] [] [IntegrationTest-akka.actor.default-dispatcher-8] - Remoting started with transport [Artery tcp]; listening on address [akka://IntegrationTest@127.0.0.1:39721] with UID [-5292613343339632714]
299[2020-10-22 09:43:47,421] [INFO] [akka.cluster.Cluster] [akka://IntegrationTest@127.0.0.1:39721] [] [IntegrationTest-akka.actor.default-dispatcher-8] - Cluster Node [akka://IntegrationTest@127.0.0.1:39721] - Starting up, Akka version [2.6.10] ...
300[2020-10-22 09:43:47,435] [INFO] [akka.cluster.Cluster] [akka://IntegrationTest@127.0.0.1:39721] [] [IntegrationTest-akka.actor.default-dispatcher-8] - Cluster Node [akka://IntegrationTest@127.0.0.1:39721] - Registered cluster JMX MBean [akka:type=Cluster,port=39721]
301[2020-10-22 09:43:47,443] [INFO] [akka.cluster.Cluster] [akka://IntegrationTest@127.0.0.1:39721] [] [IntegrationTest-akka.actor.default-dispatcher-8] - Cluster Node [akka://IntegrationTest@127.0.0.1:39721] - Started up successfully
302[2020-10-22 09:43:47,457] [INFO] [akka.cluster.Cluster] [akka://IntegrationTest@127.0.0.1:39721] [] [IntegrationTest-akka.actor.default-dispatcher-3] - Cluster Node [akka://IntegrationTest@127.0.0.1:39721] - No seed-nodes configured, manual cluster join required, see https://doc.akka.io/docs/akka/current/typed/cluster.html#joining
303[2020-10-22 09:43:47,460] [INFO] [akka.cluster.sbr.SplitBrainResolver] [akka://IntegrationTest@127.0.0.1:39721] [] [IntegrationTest-akka.actor.default-dispatcher-8] - SBR started. Config: strategy [KeepMajority], stable-after [20 seconds], down-all-when-unstable [15 seconds], selfUniqueAddress [akka://IntegrationTest@127.0.0.1:39721#-5292613343339632714], selfDc [default].
304[2020-10-22 09:43:47,642] [INFO] [akka.event.slf4j.Slf4jLogger] [] [] [IntegrationTest-akka.actor.default-dispatcher-3] - Slf4jLogger started
305[2020-10-22 09:43:47,691] [INFO] [akka.remote.artery.tcp.ArteryTcpTransport] [akka://IntegrationTest@127.0.0.1:40521] [] [IntegrationTest-akka.actor.default-dispatcher-3] - Remoting started with transport [Artery tcp]; listening on address [akka://IntegrationTest@127.0.0.1:40521] with UID [4046103915606214667]
306[2020-10-22 09:43:47,699] [INFO] [akka.cluster.Cluster] [akka://IntegrationTest@127.0.0.1:40521] [] [IntegrationTest-akka.actor.default-dispatcher-3] - Cluster Node [akka://IntegrationTest@127.0.0.1:40521] - Starting up, Akka version [2.6.10] ...
307[2020-10-22 09:43:47,706] [INFO] [akka.cluster.Cluster] [akka://IntegrationTest@127.0.0.1:40521] [] [IntegrationTest-akka.actor.default-dispatcher-3] - Cluster Node [akka://IntegrationTest@127.0.0.1:40521] - Registered cluster JMX MBean [akka:type=Cluster,port=40521]
308[2020-10-22 09:43:47,706] [INFO] [akka.cluster.Cluster] [akka://IntegrationTest@127.0.0.1:40521] [] [IntegrationTest-akka.actor.default-dispatcher-3] - Cluster Node [akka://IntegrationTest@127.0.0.1:40521] - Started up successfully
309[2020-10-22 09:43:47,719] [INFO] [akka.cluster.Cluster] [akka://IntegrationTest@127.0.0.1:40521] [] [IntegrationTest-akka.actor.default-dispatcher-6] - Cluster Node [akka://IntegrationTest@127.0.0.1:40521] - No seed-nodes configured, manual cluster join required, see https://doc.akka.io/docs/akka/current/typed/cluster.html#joining
310[2020-10-22 09:43:47,720] [INFO] [akka.cluster.sbr.SplitBrainResolver] [akka://IntegrationTest@127.0.0.1:40521] [] [IntegrationTest-akka.actor.default-dispatcher-6] - SBR started. Config: strategy [KeepMajority], stable-after [20 seconds], down-all-when-unstable [15 seconds], selfUniqueAddress [akka://IntegrationTest@127.0.0.1:40521#4046103915606214667], selfDc [default].
311[2020-10-22 09:43:47,870] [INFO] [akka.persistence.Persistence] [akka://IntegrationTest@127.0.0.1:44325] [] [IntegrationTest-akka.actor.default-dispatcher-3] - Auto-starting journal plugin `akka.persistence.cassandra.journal`
312[2020-10-22 09:43:48,481] [WARN] [akka.persistence.cassandra.query.scaladsl.CassandraReadJournal] [akka://IntegrationTest@127.0.0.1:44325] [] [IntegrationTest-akka.actor.default-dispatcher-3] - EventsByTag eventual consistency set below 1 second. This is likely to result in missed events. See reference.conf for details.
313[2020-10-22 09:43:51,923] [INFO] [akka.management.internal.HealthChecksImpl] [akka://IntegrationTest@127.0.0.1:44325] [] [IntegrationTest-akka.actor.default-dispatcher-5] - Loading readiness checks [(akka-persistence-cassandra,akka.persistence.cassandra.healthcheck.CassandraHealthCheck), (cluster-membership,akka.management.cluster.scaladsl.ClusterMembershipCheck), (sharding,akka.cluster.sharding.ClusterShardingHealthCheck)]
314[2020-10-22 09:43:51,924] [INFO] [akka.management.internal.HealthChecksImpl] [akka://IntegrationTest@127.0.0.1:44325] [] [IntegrationTest-akka.actor.default-dispatcher-5] - Loading liveness checks []
315[2020-10-22 09:43:51,929] [INFO] [akka.management.internal.HealthChecksImpl] [akka://IntegrationTest@127.0.0.1:39721] [] [IntegrationTest-akka.actor.default-dispatcher-7] - Loading readiness checks [(akka-persistence-cassandra,akka.persistence.cassandra.healthcheck.CassandraHealthCheck), (cluster-membership,akka.management.cluster.scaladsl.ClusterMembershipCheck), (sharding,akka.cluster.sharding.ClusterShardingHealthCheck)]
316[2020-10-22 09:43:51,929] [INFO] [akka.management.internal.HealthChecksImpl] [akka://IntegrationTest@127.0.0.1:39721] [] [IntegrationTest-akka.actor.default-dispatcher-7] - Loading liveness checks []
317[2020-10-22 09:43:51,945] [INFO] [akka.persistence.Persistence] [akka://IntegrationTest@127.0.0.1:39721] [] [IntegrationTest-akka.actor.default-dispatcher-7] - Auto-starting journal plugin `akka.persistence.cassandra.journal`
318[2020-10-22 09:43:51,963] [INFO] [akka.management.internal.HealthChecksImpl] [akka://IntegrationTest@127.0.0.1:40521] [] [IntegrationTest-akka.actor.default-dispatcher-3] - Loading readiness checks [(akka-persistence-cassandra,akka.persistence.cassandra.healthcheck.CassandraHealthCheck), (cluster-membership,akka.management.cluster.scaladsl.ClusterMembershipCheck), (sharding,akka.cluster.sharding.ClusterShardingHealthCheck)]
319[2020-10-22 09:43:51,963] [INFO] [akka.management.internal.HealthChecksImpl] [akka://IntegrationTest@127.0.0.1:40521] [] [IntegrationTest-akka.actor.default-dispatcher-3] - Loading liveness checks []
320[2020-10-22 09:43:51,976] [INFO] [akka.persistence.Persistence] [akka://IntegrationTest@127.0.0.1:40521] [] [IntegrationTest-akka.actor.default-dispatcher-3] - Auto-starting journal plugin `akka.persistence.cassandra.journal`
321[2020-10-22 09:43:52,069] [WARN] [akka.persistence.cassandra.query.scaladsl.CassandraReadJournal] [akka://IntegrationTest@127.0.0.1:39721] [] [IntegrationTest-akka.actor.default-dispatcher-7] - EventsByTag eventual consistency set below 1 second. This is likely to result in missed events. See reference.conf for details.
322[2020-10-22 09:43:52,096] [WARN] [akka.persistence.cassandra.query.scaladsl.CassandraReadJournal] [akka://IntegrationTest@127.0.0.1:40521] [] [IntegrationTest-akka.actor.default-dispatcher-3] - EventsByTag eventual consistency set below 1 second. This is likely to result in missed events. See reference.conf for details.
323[2020-10-22 09:43:52,579] [INFO] [akka.management.scaladsl.AkkaManagement] [akka://IntegrationTest@127.0.0.1:39721] [] [IntegrationTest-akka.actor.default-dispatcher-8] - Binding Akka Management (HTTP) endpoint to: 127.0.0.1:33197
324[2020-10-22 09:43:52,580] [INFO] [akka.management.scaladsl.AkkaManagement] [akka://IntegrationTest@127.0.0.1:40521] [] [IntegrationTest-akka.actor.default-dispatcher-3] - Binding Akka Management (HTTP) endpoint to: 127.0.0.1:40185
325[2020-10-22 09:43:52,584] [INFO] [akka.management.scaladsl.AkkaManagement] [akka://IntegrationTest@127.0.0.1:44325] [] [IntegrationTest-akka.actor.default-dispatcher-14] - Binding Akka Management (HTTP) endpoint to: 127.0.0.1:38177
326[2020-10-22 09:43:53,006] [INFO] [akka.management.scaladsl.AkkaManagement] [akka://IntegrationTest@127.0.0.1:39721] [] [IntegrationTest-akka.actor.default-dispatcher-8] - Including HTTP management routes for ClusterHttpManagementRouteProvider
327[2020-10-22 09:43:53,014] [INFO] [akka.management.scaladsl.AkkaManagement] [akka://IntegrationTest@127.0.0.1:40521] [] [IntegrationTest-akka.actor.default-dispatcher-13] - Including HTTP management routes for ClusterHttpManagementRouteProvider
328[2020-10-22 09:43:53,026] [INFO] [akka.management.scaladsl.AkkaManagement] [akka://IntegrationTest@127.0.0.1:44325] [] [IntegrationTest-akka.actor.default-dispatcher-15] - Including HTTP management routes for ClusterHttpManagementRouteProvider
329[2020-10-22 09:43:53,092] [INFO] [akka.management.scaladsl.AkkaManagement] [akka://IntegrationTest@127.0.0.1:39721] [] [IntegrationTest-akka.actor.default-dispatcher-8] - Including HTTP management routes for ClusterBootstrap
330[2020-10-22 09:43:53,093] [INFO] [akka.management.scaladsl.AkkaManagement] [akka://IntegrationTest@127.0.0.1:40521] [] [IntegrationTest-akka.actor.default-dispatcher-13] - Including HTTP management routes for ClusterBootstrap
331[2020-10-22 09:43:53,100] [INFO] [akka.management.cluster.bootstrap.ClusterBootstrap] [akka://IntegrationTest@127.0.0.1:40521] [] [IntegrationTest-akka.actor.default-dispatcher-13] - Using self contact point address: http://127.0.0.1:40185
332[2020-10-22 09:43:53,102] [INFO] [akka.management.scaladsl.AkkaManagement] [akka://IntegrationTest@127.0.0.1:44325] [] [IntegrationTest-akka.actor.default-dispatcher-15] - Including HTTP management routes for ClusterBootstrap
333[2020-10-22 09:43:53,104] [INFO] [akka.management.cluster.bootstrap.ClusterBootstrap] [akka://IntegrationTest@127.0.0.1:39721] [] [IntegrationTest-akka.actor.default-dispatcher-8] - Using self contact point address: http://127.0.0.1:33197
334[2020-10-22 09:43:53,106] [INFO] [akka.management.cluster.bootstrap.ClusterBootstrap] [akka://IntegrationTest@127.0.0.1:44325] [] [IntegrationTest-akka.actor.default-dispatcher-15] - Using self contact point address: http://127.0.0.1:38177
335[2020-10-22 09:43:53,139] [INFO] [akka.management.scaladsl.AkkaManagement] [akka://IntegrationTest@127.0.0.1:44325] [] [IntegrationTest-akka.actor.default-dispatcher-15] - Including HTTP management routes for HealthCheckRoutes
336[2020-10-22 09:43:53,139] [INFO] [akka.management.scaladsl.AkkaManagement] [akka://IntegrationTest@127.0.0.1:40521] [] [IntegrationTest-akka.actor.default-dispatcher-13] - Including HTTP management routes for HealthCheckRoutes
337[2020-10-22 09:43:53,150] [INFO] [akka.management.scaladsl.AkkaManagement] [akka://IntegrationTest@127.0.0.1:39721] [] [IntegrationTest-akka.actor.default-dispatcher-8] - Including HTTP management routes for HealthCheckRoutes
338[2020-10-22 09:43:53,759] [INFO] [akka.management.cluster.bootstrap.ClusterBootstrap] [akka://IntegrationTest@127.0.0.1:39721] [] [IntegrationTest-akka.actor.default-dispatcher-7] - Initiating bootstrap procedure using config method...
339[2020-10-22 09:43:53,766] [INFO] [akka.management.cluster.bootstrap.ClusterBootstrap] [akka://IntegrationTest@127.0.0.1:44325] [] [IntegrationTest-akka.actor.default-dispatcher-5] - Initiating bootstrap procedure using config method...
340[2020-10-22 09:43:53,772] [INFO] [akka.management.scaladsl.AkkaManagement] [akka://IntegrationTest@127.0.0.1:39721] [akkaManagementBound] [IntegrationTest-akka.actor.default-dispatcher-7] - Bound Akka Management (HTTP) endpoint to: 127.0.0.1:33197
341[2020-10-22 09:43:53,773] [INFO] [akka.management.cluster.bootstrap.ClusterBootstrap] [akka://IntegrationTest@127.0.0.1:40521] [] [IntegrationTest-akka.actor.default-dispatcher-3] - Initiating bootstrap procedure using config method...
342[2020-10-22 09:43:53,775] [INFO] [akka.management.scaladsl.AkkaManagement] [akka://IntegrationTest@127.0.0.1:44325] [akkaManagementBound] [IntegrationTest-akka.actor.default-dispatcher-5] - Bound Akka Management (HTTP) endpoint to: 127.0.0.1:38177
343[2020-10-22 09:43:53,775] [INFO] [akka.management.scaladsl.AkkaManagement] [akka://IntegrationTest@127.0.0.1:40521] [akkaManagementBound] [IntegrationTest-akka.actor.default-dispatcher-3] - Bound Akka Management (HTTP) endpoint to: 127.0.0.1:40185
344[2020-10-22 09:43:53,781] [INFO] [akka.management.cluster.bootstrap.ClusterBootstrap] [akka://IntegrationTest@127.0.0.1:44325] [] [IntegrationTest-akka.actor.default-dispatcher-15] - Bootstrap using `akka.discovery` method: config
345[2020-10-22 09:43:53,784] [INFO] [akka.management.cluster.bootstrap.ClusterBootstrap] [akka://IntegrationTest@127.0.0.1:40521] [] [IntegrationTest-akka.actor.default-dispatcher-3] - Bootstrap using `akka.discovery` method: config
346[2020-10-22 09:43:53,797] [INFO] [akka.management.cluster.bootstrap.ClusterBootstrap] [akka://IntegrationTest@127.0.0.1:39721] [] [IntegrationTest-akka.actor.default-dispatcher-8] - Bootstrap using `akka.discovery` method: config
347[2020-10-22 09:43:53,837] [INFO] [akka.management.cluster.bootstrap.internal.BootstrapCoordinator] [akka://IntegrationTest@127.0.0.1:39721] [akkaBootstrapInit] [IntegrationTest-akka.actor.default-dispatcher-7] - Locating service members. Using discovery [akka.discovery.config.ConfigServiceDiscovery], join decider [akka.management.cluster.bootstrap.LowestAddressJoinDecider], scheme [http]
348[2020-10-22 09:43:53,838] [INFO] [akka.management.cluster.bootstrap.internal.BootstrapCoordinator] [akka://IntegrationTest@127.0.0.1:39721] [] [IntegrationTest-akka.actor.default-dispatcher-7] - Looking up [Lookup(shoppingcartservice,Some(management),Some(tcp))]
349[2020-10-22 09:43:53,838] [INFO] [akka.management.cluster.bootstrap.internal.BootstrapCoordinator] [akka://IntegrationTest@127.0.0.1:39721] [akkaBootstrapResolved] [IntegrationTest-akka.actor.default-dispatcher-7] - Located service members based on: [Lookup(shoppingcartservice,Some(management),Some(tcp))]: [ResolvedTarget(127.0.0.1,Some(38177),None), ResolvedTarget(127.0.0.1,Some(33197),None)], filtered to [127.0.0.1:38177, 127.0.0.1:33197]
350[2020-10-22 09:43:53,848] [INFO] [akka.management.cluster.bootstrap.internal.BootstrapCoordinator] [akka://IntegrationTest@127.0.0.1:40521] [akkaBootstrapInit] [IntegrationTest-akka.actor.default-dispatcher-13] - Locating service members. Using discovery [akka.discovery.config.ConfigServiceDiscovery], join decider [akka.management.cluster.bootstrap.LowestAddressJoinDecider], scheme [http]
351[2020-10-22 09:43:53,848] [INFO] [akka.management.cluster.bootstrap.internal.BootstrapCoordinator] [akka://IntegrationTest@127.0.0.1:40521] [] [IntegrationTest-akka.actor.default-dispatcher-13] - Looking up [Lookup(shoppingcartservice,Some(management),Some(tcp))]
352[2020-10-22 09:43:53,849] [INFO] [akka.management.cluster.bootstrap.internal.BootstrapCoordinator] [akka://IntegrationTest@127.0.0.1:40521] [akkaBootstrapResolved] [IntegrationTest-akka.actor.default-dispatcher-13] - Located service members based on: [Lookup(shoppingcartservice,Some(management),Some(tcp))]: [ResolvedTarget(127.0.0.1,Some(38177),None), ResolvedTarget(127.0.0.1,Some(33197),None)], filtered to [127.0.0.1:38177, 127.0.0.1:33197]
353[2020-10-22 09:43:53,860] [INFO] [akka.management.cluster.bootstrap.internal.BootstrapCoordinator] [akka://IntegrationTest@127.0.0.1:44325] [akkaBootstrapInit] [IntegrationTest-akka.actor.default-dispatcher-15] - Locating service members. Using discovery [akka.discovery.config.ConfigServiceDiscovery], join decider [akka.management.cluster.bootstrap.LowestAddressJoinDecider], scheme [http]
354[2020-10-22 09:43:53,860] [INFO] [akka.management.cluster.bootstrap.internal.BootstrapCoordinator] [akka://IntegrationTest@127.0.0.1:44325] [] [IntegrationTest-akka.actor.default-dispatcher-15] - Looking up [Lookup(shoppingcartservice,Some(management),Some(tcp))]
355[2020-10-22 09:43:53,862] [INFO] [akka.management.cluster.bootstrap.internal.BootstrapCoordinator] [akka://IntegrationTest@127.0.0.1:44325] [akkaBootstrapResolved] [IntegrationTest-akka.actor.default-dispatcher-14] - Located service members based on: [Lookup(shoppingcartservice,Some(management),Some(tcp))]: [ResolvedTarget(127.0.0.1,Some(38177),None), ResolvedTarget(127.0.0.1,Some(33197),None)], filtered to [127.0.0.1:38177, 127.0.0.1:33197]
356[2020-10-22 09:43:53,927] [INFO] [akka.cluster.sharding.typed.scaladsl.ClusterSharding] [akka://IntegrationTest@127.0.0.1:39721] [] [IntegrationTest-akka.actor.default-dispatcher-18] - Starting Shard Region [ShoppingCart]...
357[2020-10-22 09:43:53,930] [INFO] [akka.cluster.sharding.typed.scaladsl.ClusterSharding] [akka://IntegrationTest@127.0.0.1:44325] [] [IntegrationTest-akka.actor.default-dispatcher-5] - Starting Shard Region [ShoppingCart]...
358[2020-10-22 09:43:53,933] [INFO] [akka.cluster.sharding.typed.scaladsl.ClusterSharding] [akka://IntegrationTest@127.0.0.1:40521] [] [IntegrationTest-akka.actor.default-dispatcher-15] - Starting Shard Region [ShoppingCart]...
359[2020-10-22 09:43:54,049] [INFO] [akka.cluster.sharding.ShardRegion] [akka://IntegrationTest@127.0.0.1:39721] [] [IntegrationTest-akka.actor.default-dispatcher-3] - ShoppingCart: Idle entities will be passivated after [2.000 min]
360[2020-10-22 09:43:54,055] [INFO] [akka.cluster.sharding.ShardRegion] [akka://IntegrationTest@127.0.0.1:40521] [] [IntegrationTest-akka.actor.default-dispatcher-17] - ShoppingCart: Idle entities will be passivated after [2.000 min]
361[2020-10-22 09:43:54,076] [INFO] [akka.cluster.sharding.ShardRegion] [akka://IntegrationTest@127.0.0.1:44325] [] [IntegrationTest-akka.actor.default-dispatcher-19] - ShoppingCart: Idle entities will be passivated after [2.000 min]
362[2020-10-22 09:43:54,664] [INFO] [akka.management.cluster.bootstrap.contactpoint.HttpClusterBootstrapRoutes] [akka://IntegrationTest@127.0.0.1:39721] [] [IntegrationTest-akka.actor.default-dispatcher-19] - Bootstrap request from 127.0.0.1:57942: Contact Point returning 0 seed-nodes []
363[2020-10-22 09:43:54,672] [INFO] [akka.management.cluster.bootstrap.contactpoint.HttpClusterBootstrapRoutes] [akka://IntegrationTest@127.0.0.1:39721] [] [IntegrationTest-akka.actor.default-dispatcher-19] - Bootstrap request from 127.0.0.1:57954: Contact Point returning 0 seed-nodes []
364[2020-10-22 09:43:54,673] [INFO] [akka.management.cluster.bootstrap.contactpoint.HttpClusterBootstrapRoutes] [akka://IntegrationTest@127.0.0.1:39721] [] [IntegrationTest-akka.actor.default-dispatcher-19] - Bootstrap request from 127.0.0.1:57946: Contact Point returning 0 seed-nodes []
365[2020-10-22 09:43:54,673] [INFO] [akka.management.cluster.bootstrap.contactpoint.HttpClusterBootstrapRoutes] [akka://IntegrationTest@127.0.0.1:44325] [] [IntegrationTest-akka.actor.default-dispatcher-19] - Bootstrap request from 127.0.0.1:56820: Contact Point returning 0 seed-nodes []
366[2020-10-22 09:43:54,673] [INFO] [akka.management.cluster.bootstrap.contactpoint.HttpClusterBootstrapRoutes] [akka://IntegrationTest@127.0.0.1:44325] [] [IntegrationTest-akka.actor.default-dispatcher-19] - Bootstrap request from 127.0.0.1:56812: Contact Point returning 0 seed-nodes []
367[2020-10-22 09:43:54,678] [INFO] [akka.management.cluster.bootstrap.contactpoint.HttpClusterBootstrapRoutes] [akka://IntegrationTest@127.0.0.1:44325] [] [IntegrationTest-akka.actor.default-dispatcher-19] - Bootstrap request from 127.0.0.1:56818: Contact Point returning 0 seed-nodes []
368[2020-10-22 09:43:54,733] [ERROR] [akka.io.TcpListener] [akka://IntegrationTest@127.0.0.1:44325] [] [IntegrationTest-akka.actor.default-dispatcher-19] - Bind failed for TCP channel on endpoint [localhost/127.0.0.1:39721]
369java.net.BindException: [localhost/127.0.0.1:39721] Address already in use
370	at java.base/sun.nio.ch.Net.bind0(Native Method)
371	at java.base/sun.nio.ch.Net.bind(Net.java:455)
372	at java.base/sun.nio.ch.Net.bind(Net.java:447)
373	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
374	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
375	at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:60)
376	at akka.io.TcpListener.<init>(TcpListener.scala:57)
377	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
378	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
379	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
380	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
381	at akka.util.Reflect$.instantiate(Reflect.scala:73)
382	at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:101)
383	at akka.actor.Props.newActor(Props.scala:226)
384	at akka.actor.ActorCell.newActor(ActorCell.scala:613)
385	at akka.actor.ActorCell.create(ActorCell.scala:640)
386	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:513)
387	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:535)
388	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
389	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
390	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
```

**Comment by patriknw** [comment]
another https://travis-ci.com/github/akka/akka-platform-guide/jobs/407158130

**Comment by patriknw** [comment]
duplicate in https://github.com/akka/akka-platform-guide/issues/564
