### ISSUE TITLE
failed: ItemPopularityIntegrationTest: expected:<9> but was:<5>

### ISSUE THREAD

**Issue by patriknw** [akka/akka-platform-guide#534]
https://github.com/akka/akka-platform-guide/pull/531/checks?check_run_id=1791316864

```
[2021-01-29 12:00:50,365] [WARN] [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] [] [] [ItemPopularityIntegrationTest-akka.projection.jdbc.blocking-jdbc-dispatcher-34] - SQL Error: 0, SQLState: 23505
122
Error: 1-29 12:00:50,365] [ERROR] [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] [] [] [ItemPopularityIntegrationTest-akka.projection.jdbc.blocking-jdbc-dispatcher-34] - ERROR: duplicate key value violates unique constraint "item_popularity_pkey"
123
  Detail: Key (itemid)=(item2) already exists.
124
Error: 1-29 12:00:50,391] [ERROR] [akka.projection.jdbc.internal.JdbcProjectionImpl$JdbcInternalProjectionState] [akka://ItemPopularityIntegrationTest@127.0.0.1:44739] [] [ItemPopularityIntegrationTest-akka.actor.default-dispatcher-22] - [ItemPopularityProjection-carts-1] Failed to process envelope with offset [Sequence(3)]. Projection will stop as defined by recovery strategy.
125
org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [item_popularity_pkey]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
126
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:276)
127
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:233)
128
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:566)
129
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:743)
130
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
131
	at shopping.cart.repository.HibernateJdbcSession.commit(HibernateJdbcSession.java:61)
132
	at akka.projection.jdbc.internal.JdbcSessionUtil$.$anonfun$withSession$1(JdbcSessionUtil.scala:34)
133
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:671)
134
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
135
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
136
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
137
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
138
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
139
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
140
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
141
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
142
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
143
	at java.base/java.lang.Thread.run(Thread.java:834)
144
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
145
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:109)
146
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
147
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
148
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
149
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:200)
150
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3235)
201
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
202
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
203
	at java.base/java.lang.Thread.run(Thread.java:834)
204
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
205
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:109)
206
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
207
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
208
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
209
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:200)
210
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3235)
211
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3760)
212
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:107)
213
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
214
	at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478)
215
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
216
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475)
217
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:348)
218
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40)
219
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:102)
220
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1352)
221
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:443)
222
	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3202)
223
	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2370)
224
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:447)
225
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:183)
226
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$300(JdbcResourceLocalTransactionCoordinatorImpl.java:40)
227
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:281)
228
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101)
229
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:562)
230
	... 15 more
231
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "item_popularity_pkey"
232
  Detail: Key (itemid)=(item2) already exists.
233
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
234
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
235
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
236
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
237
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
238
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
239
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:130)
240
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
241
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
242
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
243
	... 35 more
244
```

**Comment by patriknw** [comment]
another here https://github.com/akka/akka-platform-guide/runs/1804957532?check_suite_focus=true
(after merging back to main)

**Comment by patriknw** [comment]
this is failing frequently

**Comment by ignasi35** [comment]
Even on a PR (https://github.com/akka/akka-platform-guide/pull/554/checks?check_run_id=1854756734).
