### ISSUE TITLE
failed: ItemPopularityIntegrationTest: expected:<9> but was:<5>

### ISSUE THREAD

**Issue by patriknw** [akka/akka-platform-guide#578]
I thought we had fixed this in https://github.com/akka/akka-platform-guide/issues/534 but it's still failing

```
21-02-15T09:51:05.8458079Z Failed tests:   consumeCartEventsAndUpdatePopularityCount(shopping.cart.ItemPopularityIntegrationTest): expected:<9> but was:<5>
```

**Comment by ignasi35** [comment]
I suspect we are running tests in parallel and the actor system from `ItemPopularityIntegrationTest` is joining the cluster from `IntegrationTest` or is shutdown when that cluster shutsdown.

see 

```
2021-02-15T09:50:47.7787540Z [2021-02-15 09:50:47,777] [INFO] [akka.management.scaladsl.AkkaManagement] [akka://IntegrationTest@127.0.0.1:38819] [] [IntegrationTest-akka.actor.default-dispatcher-6] - Binding Akka Management (HTTP) endpoint to: 127.0.0.1:34265
2021-02-15T09:50:47.7798860Z [2021-02-15 09:50:47,779] [INFO] [akka.management.scaladsl.AkkaManagement] [akka://IntegrationTest@127.0.0.1:36589] [] [IntegrationTest-akka.actor.default-dispatcher-6] - Binding Akka Management (HTTP) endpoint to: 127.0.0.1:41427
2021-02-15T09:50:47.7858680Z [2021-02-15 09:50:47,785] [INFO] [akka.management.scaladsl.AkkaManagement] [akka://IntegrationTest@127.0.0.1:41181] [] [IntegrationTest-akka.actor.default-dispatcher-3] - Binding Akka Management (HTTP) endpoint to: 127.0.0.1:34395
```

**Comment by patriknw** [comment]
I messed up and took the output from wrong test, and now I can't find the failed build anymore. We'll have to wait until it happens again.

**Comment by ignasi35** [comment]
Seen it again:

```
...
[2021-02-25 11:56:54,313] [INFO] [com.zaxxer.hikari.HikariDataSource] [] [] [ItemPopularityIntegrationTest-akka.actor.default-dispatcher-20] - db - Shutdown initiated...
[2021-02-25 11:56:54,321] [INFO] [com.zaxxer.hikari.HikariDataSource] [] [] [ItemPopularityIntegrationTest-akka.actor.default-dispatcher-20] - db - Shutdown completed.
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 16.124 sec <<< FAILURE!
consumeCartEventsAndUpdatePopularityCount(shopping.cart.ItemPopularityIntegrationTest)  Time elapsed: 11.923 sec  <<< FAILURE!
java.lang.AssertionError: expected:<9> but was:<5>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at shopping.cart.ItemPopularityIntegrationTest.lambda$consumeCartEventsAndUpdatePopularityCount$e3b33215$2(ItemPopularityIntegrationTest.java:110)
	at akka.actor.testkit.typed.internal.TestProbeImpl.$anonfun$awaitAssert$1(TestProbeImpl.scala:348)
	at akka.actor.testkit.typed.internal.TestProbeImpl.poll$1(TestProbeImpl.scala:366)
	at akka.actor.testkit.typed.internal.TestProbeImpl.awaitAssert_internal(TestProbeImpl.scala:383)
	at akka.actor.testkit.typed.internal.TestProbeImpl.awaitAssert(TestProbeImpl.scala:348)
	at akka.actor.testkit.typed.internal.TestProbeImpl.awaitAssert(TestProbeImpl.scala:351)
	at shopping.cart.ItemPopularityIntegrationTest.consumeCartEventsAndUpdatePopularityCount(ItemPopularityIntegrationTest.java:105)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
...
```

**Comment by ignasi35** [comment]
Something phishy is going on here. When I force a collision on the primary key I see a failure on the logs and the projection handler restarting:

 - forcing the PK violation on a local run:

```
[2021-02-25 14:41:09,542] [INFO] [shopping.cart.ItemPopularityProjectionHandler] [] [] [ItemPopularityIntegrationTest-akka.projection.jdbc.blocking-jdbc-dispatcher-59] - ItemPopularityProjectionHandler(carts-1) item popularity for 'item2': [4]
[2021-02-25 14:41:09,586] [INFO] [shopping.cart.ItemPopularityProjectionHandler] [] [] [ItemPopularityIntegrationTest-akka.projection.jdbc.blocking-jdbc-dispatcher-60] - ItemPopularityProjectionHandler(carts-0) item popularity for 'item2': [5]
[2021-02-25 14:41:09,594] [WARN] [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] [] [] [ItemPopularityIntegrationTest-akka.projection.jdbc.blocking-jdbc-dispatcher-60] - SQL Error: 0, SQLState: 23505
[2021-02-25 14:41:09,594] [ERROR] [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] [] [] [ItemPopularityIntegrationTest-akka.projection.jdbc.blocking-jdbc-dispatcher-60] - ERROR: duplicate key value violates unique constraint "item_popularity_pkey"
  Detail: Key (itemid)=(item2) already exists.
[2021-02-25 14:41:09,614] [ERROR] [akka.projection.jdbc.internal.JdbcProjectionImpl$JdbcInternalProjectionState] [akka://ItemPopularityIntegrationTest@127.0.0.1:61013] [] [ItemPopularityIntegrationTest-akka.actor.default-dispatcher-42] - [ItemPopularityProjection-carts-0] Failed to process envelope with offset [Sequence(2)]. Projection will stop as defined by recovery strategy.
org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [item_popularity_pkey]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:276)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:233)
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:566)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:743)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
	at shopping.cart.repository.HibernateJdbcSession.commit(HibernateJdbcSession.java:61)
```

But that's not what's happening on the Github Actions:

```
[2021-02-25 11:56:41,629] [INFO] [akka.projection.ProjectionBehavior$] [akka://ItemPopularityIntegrationTest@127.0.0.1:46787] [] [ItemPopularityIntegrationTest-akka.actor.default-dispatcher-7] - Starting projection [ProjectionId(ItemPopularityProjection, carts-2)]
[2021-02-25 11:56:43,181] [INFO] [shopping.cart.ItemPopularityProjectionHandler] [] [] [ItemPopularityIntegrationTest-akka.projection.jdbc.blocking-jdbc-dispatcher-33] - ItemPopularityProjectionHandler(carts-0) item popularity for 'item1': [3]
[2021-02-25 11:56:44,171] [INFO] [shopping.cart.ItemPopularityProjectionHandler] [] [] [ItemPopularityIntegrationTest-akka.projection.jdbc.blocking-jdbc-dispatcher-35] - ItemPopularityProjectionHandler(carts-1) item popularity for 'item2': [4]
[2021-02-25 11:56:44,179] [INFO] [shopping.cart.ItemPopularityProjectionHandler] [] [] [ItemPopularityIntegrationTest-akka.projection.jdbc.blocking-jdbc-dispatcher-34] - ItemPopularityProjectionHandler(carts-0) item popularity for 'item2': [5]
[2021-02-25 11:56:53,214] [INFO] [akka.cluster.sharding.DDataShardCoordinator] [akka://ItemPopularityIntegrationTest@127.0.0.1:46787] [] [ItemPopularityIntegrationTest-akka.actor.default-dispatcher-8] - ShoppingCart: Starting shutting down shards [505,506] due to region shutting down.
[2021-02-25 11:56:53,214] [INFO] [akka.cluster.sharding.DDataShardCoordinator] [akka://ItemPopularityIntegrationTest@127.0.0.1:46787] [] [ItemPopularityIntegrationTest-akka.actor.default-dispatcher-8] - sharded-daemon-process-ItemPopularityProjection: Starting shutting down shards [4,1,0,2,3] due to region shutting down.
```
What happens here is that `item popularity for 'item2': [4]` is written and after that `item popularity for 'item2': [5]` is written. I suspect the second operation does an update on the DB instead of an insert so the DB ends up with a value of `5` and no PK violation happened.

**Comment by ignasi35** [comment]
I haven't seen this fail in a while.
