### ISSUE TITLE
failed: IntegrationSpec - Broker may not be available

### ISSUE THREAD

**Issue by patriknw** [akka/akka-platform-guide#588]
Something with Kafka not available

https://github.com/akka/akka-platform-guide/pull/575/checks?check_run_id=1933884932

```
2021-02-19T08:43:15.5293126Z [2021-02-19 08:43:14,659] [INFO] [org.apache.kafka.clients.consumer.KafkaConsumer] [] [] [IntegrationSpec-akka.kafka.default-dispatcher-37] - [Consumer clientId=consumer-37a7844f-241c-4773-aa94-a9acc2b17d37-1, groupId=37a7844f-241c-4773-aa94-a9acc2b17d37] Subscribed to topic(s): shopping-cart-events
2021-02-19T08:43:15.5298316Z [2021-02-19 08:43:15,027] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [IntegrationSpec-akka.kafka.default-dispatcher-39] - [Consumer clientId=consumer-37a7844f-241c-4773-aa94-a9acc2b17d37-1, groupId=37a7844f-241c-4773-aa94-a9acc2b17d37] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2021-02-19T08:43:15.5303105Z [2021-02-19 08:43:15,028] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [IntegrationSpec-akka.kafka.default-dispatcher-39] - [Consumer clientId=consumer-37a7844f-241c-4773-aa94-a9acc2b17d37-1, groupId=37a7844f-241c-4773-aa94-a9acc2b17d37] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected
2021-02-19T08:43:15.5306848Z [2021-02-19 08:43:15,092] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [kafka-producer-network-thread | producer-2] - [Producer clientId=producer-2] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2021-02-19T08:43:15.5309617Z [2021-02-19 08:43:15,092] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [kafka-producer-network-thread | producer-2] - [Producer clientId=producer-2] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected
2021-02-19T08:43:15.5312377Z [2021-02-19 08:43:15,189] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [kafka-producer-network-thread | producer-3] - [Producer clientId=producer-3] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2021-02-19T08:43:15.5315274Z [2021-02-19 08:43:15,189] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [kafka-producer-network-thread | producer-3] - [Producer clientId=producer-3] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected
2021-02-19T08:43:15.5318017Z [2021-02-19 08:43:15,236] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [kafka-producer-network-thread | producer-1] - [Producer clientId=producer-1] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2021-02-19T08:43:15.5322298Z [2021-02-19 08:43:15,236] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [kafka-producer-network-thread | producer-1] - [Producer clientId=producer-1] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected
2021-02-19T08:43:15.5327228Z [2021-02-19 08:43:15,292] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [IntegrationSpec-akka.kafka.default-dispatcher-41] - [Consumer clientId=consumer-37a7844f-241c-4773-aa94-a9acc2b17d37-1, groupId=37a7844f-241c-4773-aa94-a9acc2b17d37] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2021-02-19T08:43:15.5334237Z [2021-02-19 08:43:15,292] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [IntegrationSpec-akka.kafka.default-dispatcher-41] - [Consumer clientId=consumer-37a7844f-241c-4773-aa94-a9acc2b17d37-1, groupId=37a7844f-241c-4773-aa94-a9acc2b17d37] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected
2021-02-19T08:43:15.5341537Z [2021-02-19 08:43:15,387] [INFO] [akka.cluster.Cluster] [akka://IntegrationSpec@127.0.0.1:33893] [] [IntegrationSpec-akka.actor.default-dispatcher-16] - Cluster Node [akka://IntegrationSpec@127.0.0.1:33893] - is the new leader among reachable nodes (more leaders may exist)
2021-02-19T08:43:15.5398164Z [2021-02-19 08:43:15,539] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [IntegrationSpec-akka.kafka.default-dispatcher-45] - [Consumer clientId=consumer-37a7844f-241c-4773-aa94-a9acc2b17d37-1, groupId=37a7844f-241c-4773-aa94-a9acc2b17d37] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2021-02-19T08:43:15.5442904Z [2021-02-19 08:43:15,543] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [IntegrationSpec-akka.kafka.default-dispatcher-45] - [Consumer clientId=consumer-37a7844f-241c-4773-aa94-a9acc2b17d37-1, groupId=37a7844f-241c-4773-aa94-a9acc2b17d37] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected
2021-02-19T08:43:15.7546110Z [2021-02-19 08:43:15,753] [INFO] [shopping.cart.ShoppingCartServiceImpl] [] [] [IntegrationSpec-akka.actor.default-dispatcher-20] - addItem foo to cart cart-1
2021-02-19T08:43:15.7830424Z [2021-02-19 08:43:15,782] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [IntegrationSpec-akka.kafka.default-dispatcher-51] - [Consumer clientId=consumer-37a7844f-241c-4773-aa94-a9acc2b17d37-1, groupId=37a7844f-241c-4773-aa94-a9acc2b17d37] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2021-02-19T08:43:15.7837702Z [2021-02-19 08:43:15,783] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [IntegrationSpec-akka.kafka.default-dispatcher-51] - [Consumer clientId=consumer-37a7844f-241c-4773-aa94-a9acc2b17d37-1, groupId=37a7844f-241c-4773-aa94-a9acc2b17d37] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected
2021-02-19T08:43:15.9825503Z [2021-02-19 08:43:15,981] [INFO] [shopping.cart.ItemPopularityProjectionHandler] [] [] [IntegrationSpec-akka.projection.jdbc.blocking-jdbc-dispatcher-40] - ItemPopularityProjectionHandler(carts-1) item popularity for 'foo': [42]
2021-02-19T08:43:16.1664877Z [2021-02-19 08:43:16,165] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [kafka-producer-network-thread | producer-2] - [Producer clientId=producer-2] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2021-02-19T08:43:16.1667913Z [2021-02-19 08:43:16,166] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [kafka-producer-network-thread | producer-2] - [Producer clientId=producer-2] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected
2021-02-19T08:43:16.2050717Z [2021-02-19 08:43:16,204] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [IntegrationSpec-akka.kafka.default-dispatcher-46] - [Consumer clientId=consumer-37a7844f-241c-4773-aa94-a9acc2b17d37-1, groupId=37a7844f-241c-4773-aa94-a9acc2b17d37] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2021-02-19T08:43:16.2055791Z [2021-02-19 08:43:16,204] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [IntegrationSpec-akka.kafka.default-dispatcher-46] - [Consumer clientId=consumer-37a7844f-241c-4773-aa94-a9acc2b17d37-1, groupId=37a7844f-241c-4773-aa94-a9acc2b17d37] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected
2021-02-19T08:43:16.3833510Z [2021-02-19 08:43:16,382] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [kafka-producer-network-thread | producer-3] - [Producer clientId=producer-3] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2021-02-19T08:43:16.3837634Z [2021-02-19 08:43:16,382] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [kafka-producer-network-thread | producer-3] - [Producer clientId=producer-3] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected
2021-02-19T08:43:16.4174674Z [2021-02-19 08:43:16,416] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [kafka-producer-network-thread | producer-1] - [Producer clientId=producer-1] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2021-02-19T08:43:16.4178054Z [2021-02-19 08:43:16,417] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [kafka-producer-network-thread | producer-1] - [Producer clientId=producer-1] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected
2021-02-19T08:43:17.1152034Z [2021-02-19 08:43:17,114] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [IntegrationSpec-akka.kafka.default-dispatcher-41] - [Consumer clientId=consumer-37a7844f-241c-4773-aa94-a9acc2b17d37-1, groupId=37a7844f-241c-4773-aa94-a9acc2b17d37] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2021-02-19T08:43:17.1156857Z [2021-02-19 08:43:17,114] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [IntegrationSpec-akka.kafka.default-dispatcher-41] - [Consumer clientId=consumer-37a7844f-241c-4773-aa94-a9acc2b17d37-1, groupId=37a7844f-241c-4773-aa94-a9acc2b17d37] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected
2021-02-19T08:43:17.2709938Z [2021-02-19 08:43:17,270] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [kafka-producer-network-thread | producer-1] - [Producer clientId=producer-1] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2021-02-19T08:43:17.2714183Z [2021-02-19 08:43:17,270] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [kafka-producer-network-thread | producer-1] - [Producer clientId=producer-1] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected
2021-02-19T08:43:17.3208008Z [2021-02-19 08:43:17,320] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [kafka-producer-network-thread | producer-2] - [Producer clientId=producer-2] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2021-02-19T08:43:17.3210969Z [2021-02-19 08:43:17,320] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [kafka-producer-network-thread | producer-2] - [Producer clientId=producer-2] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected
2021-02-19T08:43:17.4373045Z [2021-02-19 08:43:17,436] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [kafka-producer-network-thread | producer-3] - [Producer clientId=producer-3] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2021-02-19T08:43:17.4375730Z [2021-02-19 08:43:17,436] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [kafka-producer-network-thread | producer-3] - [Producer clientId=producer-3] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected
2021-02-19T08:43:18.1652068Z [2021-02-19 08:43:18,164] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [IntegrationSpec-akka.kafka.default-dispatcher-38] - [Consumer clientId=consumer-37a7844f-241c-4773-aa94-a9acc2b17d37-1, groupId=37a7844f-241c-4773-aa94-a9acc2b17d37] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2021-02-19T08:43:18.1656767Z [2021-02-19 08:43:18,164] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [IntegrationSpec-akka.kafka.default-dispatcher-38] - [Consumer clientId=consumer-37a7844f-241c-4773-aa94-a9acc2b17d37-1, groupId=37a7844f-241c-4773-aa94-a9acc2b17d37] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected
2021-02-19T08:43:18.4409831Z [2021-02-19 08:43:18,440] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [kafka-producer-network-thread | producer-3] - [Producer clientId=producer-3] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2021-02-19T08:43:18.4412715Z [2021-02-19 08:43:18,440] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [kafka-producer-network-thread | producer-3] - [Producer clientId=producer-3] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected
2021-02-19T08:43:18.4753549Z [2021-02-19 08:43:18,474] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [kafka-producer-network-thread | producer-1] - [Producer clientId=producer-1] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2021-02-19T08:43:18.4756545Z [2021-02-19 08:43:18,475] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [kafka-producer-network-thread | producer-1] - [Producer clientId=producer-1] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected
2021-02-19T08:43:18.5255557Z [2021-02-19 08:43:18,525] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [kafka-producer-network-thread | producer-2] - [Producer clientId=producer-2] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2021-02-19T08:43:18.5258686Z [2021-02-19 08:43:18,525] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [kafka-producer-network-thread | producer-2] - [Producer clientId=producer-2] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected
2021-02-19T08:43:19.3945985Z [2021-02-19 08:43:19,393] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [IntegrationSpec-akka.kafka.default-dispatcher-41] - [Consumer clientId=consumer-37a7844f-241c-4773-aa94-a9acc2b17d37-1, groupId=37a7844f-241c-4773-aa94-a9acc2b17d37] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2021-02-19T08:43:19.3951109Z [2021-02-19 08:43:19,394] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [IntegrationSpec-akka.kafka.default-dispatcher-41] - [Consumer clientId=consumer-37a7844f-241c-4773-aa94-a9acc2b17d37-1, groupId=37a7844f-241c-4773-aa94-a9acc2b17d37] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected

...

2021-02-19T08:43:35.6414972Z [2021-02-19 08:43:35,641] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [kafka-producer-network-thread | producer-2] - [Producer clientId=producer-2] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2021-02-19T08:43:35.6418371Z [2021-02-19 08:43:35,641] [WARN] [org.apache.kafka.clients.NetworkClient] [] [] [kafka-producer-network-thread | producer-2] - [Producer clientId=producer-2] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected
2021-02-19T08:43:35.9209743Z [info] - should update and project from different nodes via gRPC *** FAILED *** (21 seconds, 397 milliseconds)
2021-02-19T08:43:35.9228020Z [info]   java.lang.AssertionError: Timeout (20 seconds) during expectMessageClass waiting for class shopping.cart.proto.ItemAdded
2021-02-19T08:43:35.9238938Z [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:391)
2021-02-19T08:43:35.9252543Z [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessageClass_internal(TestProbeImpl.scala:238)
2021-02-19T08:43:35.9259167Z [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessageType(TestProbeImpl.scala:220)
2021-02-19T08:43:35.9264581Z [info]   at shopping.cart.IntegrationSpec.$anonfun$new$6(IntegrationSpec.scala:218)

```

**Comment by ignasi35** [comment]
Again https://github.com/akka/akka-platform-guide/pull/611/checks?check_run_id=2033789315#step:7:853

**Comment by ignasi35** [comment]
This is happening veeery often (I'm not pasting all the occurrences, too many)
